name: End-to-end Browser Tests

on:
  push:
    branches: [main,master,'feature/*']
  # pull_request:
  #   branches: [main,master]

jobs:
  cypress:
    name: Run Cypress Test
    runs-on: ubuntu-latest
    steps:      

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
            node-version: '18.x'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check formatting and linting
        run: |
          echo checking for formatting and linting issues...

      - name: Run npm install, build, and unit tests
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      # - name: Run App
      #   run: |
      #     npm run start

      # - name: Run Lighthouse tests
      #   run: npx lighthouse http://localhost:3000 --output json --output-path report.json

      - name: Cypress Run
        # https://github.com/marketplace/actions/cypress-io
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # config-file: cypress/cypress-base.json
          # env: WEB_APP_URI=${{steps.<ID>.outputs.<SITE_URL>}}
          start: npm start

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: screenshots
