name: End-to-end Browser Tests

on:
  push:
    branches: [main,master,'feature/*']
  # pull_request:
  #   branches: [main,master]

jobs:
  cypress:
    name: Run Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cypress Run
        # https://github.com/marketplace/actions/cypress-io
        uses: cypress-io/github-action@v6

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: screenshots
